### ISSUE TITLE
no javascript evaluated in data, only on Android, works on iOS

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#103] opened 2017-05-17 08:55 UTC
javascript in data like this
```
      "data": {
        "infive": "{{var now = new Date(); var then = new Date(now.getTime()+5*60000); then = then.toISOString(); return then;}}"
      }
```
is computed on iOS, but not on Android.

**Comment by gliechtenstein** [comment] 2017-06-15 22:35
I just tried this, and it works. There is really no reason it should work on iOS but not on Android, so if this is true we really need to fix it. But I need more info since I can't replicate this.
Please share:

1. Your full code (that's working on iOS but not on Android)
2. Screenshot of the app not working (with the console logs)
3. Your OS/device spec

p.s.

In most cases where something works on iOS but not on Android, it's because the JSON is not in a valid format. The iOS is very forgiving when parsing JSON but Android is very strict, so in many cases if you have invalid JSON it wouldn't even get to the point of render. You could check to make sure the JSON is in a valid format by trying JSON Lint.

**Comment by j2l** [comment] 2017-06-16 12:30
Ethan, thanks.
My JS is correct, my problem is: there is no javascript in `head/data`, on Android only.

**Comment by realitix** [comment] 2017-07-04 09:44
Hello @j2l. Can you post a minimal json app to reproduce the bug ?
@gliechtenstein needs a simple way to reproduce it. I can look at it too but we need the json app.

**Comment by j2l** [comment] 2017-07-04 13:07
@realitix, simply paste data in the head and call it from template or root body.
Test it on both iOS and Android.
Thanks

**Comment by realitix** [comment] 2017-07-04 14:18
@j2l I have tried that 

```
{
  "$jason": {
    "head": {
      "data": {
        "infive": "{{var now = new Date(); var then = new Date(now.getTime()+5*60000); then = then.toISOString(); return then;}}"
      },
      "title": "JS demo",
      "actions": {
        "$load": {
          "type": "$util.alert",
          "options": {
            "title": "test",
            "description": "{{infive}}"
          }
        }
      }
    }
  }
}
```

And it displays the content of `infive` (without interpreting javascript code). I don't understand what you are trying to achieve. Please paste your json, we can't help otherwise...

**Comment by j2l** [comment] 2017-07-04 14:57
now test it on iOS and report.

**Comment by gliechtenstein** [comment] 2017-07-04 16:25
@j2l please post the full JSON. Because a lot of the ways you use the JASON markup is recursive, the context really matters. The same piece of `data` object can function completely differently depending on how it's used with others.

**Comment by j2l** [comment] 2017-07-04 18:09
I tested before writing a ticket with complex and simple contexts.
Why don't you test it on iOS to see result?
Here's a full JSON, to test on iOS:
```
{
  "$jason": {
    "head": {
      "data": {
        "infive": "{{var now = new Date(); var then = new Date(now.getTime()+5*60000); then = then.toISOString(); return then;}}"
      },
      "title": "JS demo",
      "actions": {
        "$load": {
          "type": "$util.alert",
          "options": {
            "title": "test",
            "description": "{{infive}}"
          }
        }
      }
    }
  }
}
```

**Comment by j2l** [comment] 2017-07-04 18:28
Spoiler:
![screen shot 2017-07-04 at 8 27 02 pm](https://user-images.githubusercontent.com/65325/27840175-353c19c0-60f7-11e7-9eda-0c98e2dbe0f6.png)

**Comment by j2l** [comment] 2017-07-04 18:39
En même temps, je fais au plus court : titre et premier texte en une ligne. 
Mais je teste tout avant, donc faut juste tester pour comprendre :)

An eval() should do the trick but it must have a secure way.

**Comment by gliechtenstein** [comment] 2017-07-05 00:32
@j2l this is an edge case I hadn't thought about when I added the `data` attribute. The `data` attribute is meant to be used as just that, a static piece of data. The use case I had in mind was when you're delivering a huge JSON markup from the server, in many cases you can separate them into `data` and `template`, reducing the overall file size significantly. 

That said, since this is something I haven't thought about before I spent some time to think about whether to officially support this. 

Theoretically it's possible to "fix" the android code so that the dynamic expression works, but I don't think it's a good idea because it makes things complicated and I feel like it may be a source of potential bugs. In fact, even on iOS there may be problems if you use this method extensively because it was not meant to work that way. 

Plus this is something you can achieve using actions (If you're trying to set a constant variable, you can just use the `$set` action to set a local variable on `$load` event).

But I might be wrong and there are indeed cases where this is the only way you can do things. If you are running into a situation where you can't solve the problem this way, please let me know, and I'll try to figure something out.

**Comment by realitix** [comment] 2017-07-05 06:10
Nice answer @gliechtenstein. Indeed, it's not documented like that. Maybe you can close the issue for now @j2l ?

**Closed** 2017-07-05 14:27 UTC

**Comment by j2l** [comment] 2017-07-05 15:02
I should have called it [low hanging feature].
It shouldn't stay inconsistent.
Javascript is expected to be executed where it is written.
