### ISSUE TITLE
$cache.key not resolving the value

### ISSUE THREAD

**Issue by reeperbahnause** [Jasonette/JASONETTE-Android#100] opened 2017-04-26 00:27 UTC
When the app starts initially the $cache values are not resolved even though the values are set.

![image](https://cloud.githubusercontent.com/assets/14199872/25412936/b7c6d61c-2a26-11e7-875a-f9ae13004345.png)

To check if the values are really set I created an alert where the values are shown just fine.

![image](https://cloud.githubusercontent.com/assets/14199872/25413020/50d9cc88-2a27-11e7-8191-33e430aa73e1.png)

Am I missing something?

BTW this is an awesome project! 👍

**Comment by gliechtenstein** [comment] 2017-04-26 00:28
Thanks! Could you post the full json code so we can see what's wrong?

**Comment by reeperbahnause** [comment] 2017-04-26 00:38
That was a quick response ;-) 
Sure here you go!

```json
{
    "$jason": {
        "head": {
            "title": "Test App",
            "offline": "true",
            "actions": {
                "$foreground": {
                    "type": "$refresh"
                },
                "$pull": {
                    "type": "$network.request",
                    "options": {
                        "url": "http://10.0.2.2/APP/index.json"
                    },
                    "success": {
                        "type": "$render"
                    }
                }
            }
        },
        "body": {
            "header": {
                "title": "{{$cache.userObject.lastName}}",
                "style": {
                    "background": "#7EBAB5"
                }
            },
            "style": {
                "background": "#ffffff",
                "border": "none"
            },
            "sections": [
                {
                    "items": [
                        {
                            "type": "vertical",
                            "style": {
                                "padding": "30",
                                "spacing": "20",
                                "align": "center"
                            },
                            "components": [
                                {
                                    "type": "image",
                                    "url": "http://10.0.2.2/img/hand1.jpg",
                                    "style": {
                                        "width": "90%",
                                        "padding": "0",
                                        "z_index": "-1"
                                    }
                                },
                                {
                                    "type": "label",
                                    "text": "Hallo {{$cache.userObject.login}}! Just some Text {{$get.user}}",
                                    "style": {
                                        "align": "center",
                                        "font": "Courier-Bold",
                                        "size": "18"
                                    }
                                },
                                {
                                    "type": "textfield",
                                    "name": "user",
                                    "value": "{{$cache.userLogin}}",
                                    "placeholder": "Benutzer"
                                },
                                {
                                    "type": "textfield",
                                    "name": "pass",
                                    "style": {
                                        "secure": "true"
                                    },
                                    "placeholder": "Passwort"
                                },
                                {
                                    "type": "button",
                                    "text": "Anzeigen",
                                    "action": {
                                        "type": "$util.alert",
                                        "options": {
                                            "title": "Basic Alert",
                                            "description": "$cache.userObject.login = {{$cache.userObject.login}}, $cache.userObject.firstName = {{$cache.userObject.firstName}}, $cache.userObject.lastName = {{$cache.userObject.lastName}}"
                                        },
                                        "success": {
                                            "type": "$render"
                                        }
                                    }
                                },
                                {
                                    "type": "button",
                                    "text": "Anmelden",
                                    "action": {
                                        "type": "$network.request",
                                        "options": {
                                            "url": "http://10.0.2.2/API/Slim/example/loginUser",
                                            "method": "POST",
                                            "data": {
                                                "login": "{{$get.user}}",
                                                "password": "{{$get.pass}}"
                                            },
                                            "data_type": "html"
                                        },
                                        "success": {
                                            "type": "$cache.set",
                                            "options": {
                                                "userObject": "{{$jason}}",
                                                "userLogin": "{{$jason.login}}"
                                            },
                                            "success": {
                                                "type": "$util.banner",
                                                "options": {
                                                    "title": "Success",
                                                    "description": "You are logged in as User {{$cache.userObject.firstName}} {{$cache.userObject.lastName}}"
                                                }
                                            }
                                        },
                                        "error": {
                                            "type": "$util.banner",
                                            "options": {
                                                "title": "Error",
                                                "description": "Something went wrong. Please check if you entered your email and password correctly"
                                            }
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            "type": "label",
                            "style": {
                                "align": "right",
                                "padding": "10",
                                "color": "#000000",
                                "font": "HelveticaNeue",
                                "size": "12"
                            },
                            "text": "Hier gehts weiter",
                            "href": {
                                "url": "https://jasonette.github.io/Jasonpedia/demo.json",
                                "fresh": "true"
                            }
                        },
                        {
                            "type": "label",
                            "style": {
                                "align": "right",
                                "padding": "10",
                                "color": "#000000",
                                "font": "HelveticaNeue",
                                "size": "12"
                            },
                            "text": "Test",
                            "href": {
                                "url": "http://10.0.2.2/App/test.json",
                                "fresh": "true"
                            }
                        },
                        {
                            "type": "label",
                            "style": {
                                "align": "right",
                                "padding": "10",
                                "color": "#000000",
                                "font": "HelveticaNeue",
                                "size": "12"
                            },
                            "text": "Watch the tutorial video",
                            "href": {
                                "url": "https://www.youtube.com/watch?v=hfevBAAfCMQ",
                                "view": "Web"
                            }
                        },
                        {
                            "type": "label",
                            "style": {
                                "align": "right",
                                "padding": "10",
                                "color": "#000000",
                                "font": "HelveticaNeue",
                                "size": "12"
                            },
                            "text": "View documentation",
                            "href": {
                                "url": "https://jasonette.github.io/documentation",
                                "view": "Web"
                            }
                        }
                    ]
                }
            ]
        }
    }
}
```

The result from the `$network.request` looks like this:
```json
{
    "id": "17",
    "login": "Admin",
    "firstName": "System",
    "lastName": "Administrator",
    "email": "admin@system.local",
    "password": "",
    "status": "",
    "network": null,
    "networkUserId": null,
    "profileUrl": null,
    "imageurl": null,
    "company": null,
    "position": null,
    "country": null,
    "city": null,
    "street": null,
    "roles": null,
    "filters": null
}
```

**Comment by gliechtenstein** [comment] 2017-04-27 00:42
OK the problem here is you're using a template expression for the body, but you put it under `$jason.body`.

You should put them under `$jason.head.templates.body` because that's what's used for rendering when you call `$render` action.

Also there is no such action called `"type": "$refresh"`. Please refer to the documentation http://docs.jasonette.com/actions/#api for all available actions.

In this specific case, what you should be doing is, wait for the `$show` event, make the request using the `$network.request`, and then render using `$render`. (Don't forget to place the entire body under `$jason.head.templates.body`)


Here's an example

```json
{
    "$jason": {
        "head": {
            "title": "Test App",
            "offline": "true",
            "actions": {
              "$show": {
                "type": "$network.request",
                "options": {
                  "url": "http://10.0.2.2/APP/index.json"
                },
                "success": {
                  "type": "$render"
                }
              }
            },
            "templates": {
               "body": {
                 "header": {
                      "title": "{{$cache.userObject.lastName}}",
                      "style": {
                          "background": "#7EBAB5"
                      }
                 },
                 "style": {
                      "background": "#ffffff",
                      "border": "none"
                 },
                 "sections": [
                     {
                         "items": [
                             {
```

**Comment by gliechtenstein** [comment] 2017-04-27 00:43
Hope this helped! If you have further questions feel free to ask on the forum https://forum.jasonette.com

Closing since it's not a bug.

**Closed by gliechtenstein** 2017-04-27 00:43 UTC

**Comment by reeperbahnause** [comment] 2017-04-27 02:11
Thank you for your support. 
And you are right next time I will use the forum first.
Cheers Phillip
